// Generated by CoffeeScript 1.10.0
(function() {
  window.onload = function() {
    console.log(PSD);
    PSD.fromURL("JS.psd").then(function(psd) {
      var png;
      window.psd = psd;
      console.log(psd);
      console.log(png = psd.image.toPng());
      return document.body.appendChild(png);
    });
    return console.log("hello");
  };

}).call(this);
